title: נטגר
description: >- 
  עיתון מתמטי לנוער
baseurl: "/netgar"
url: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  scans:
    output: true

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
